btest/urls.py
from django.urls import path
from . import views

app_name='btest'

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('create/' , views.create, name='create'),
    path('detail/<int:btest_id>/' , views.detail , name = 'detail'),
    path('survey/<int:btest_id>/' , views.survey , name='survey'),
    path('<int:btestchild_id>/survey_mod/', views.survey_mod , name = 'survey_mod'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
   
    path('btest/' ,include('btest.urls')),
    path('crud/' , include('crud.urls')),
    path('subway/' , include('subway.urls')),
    path('admin/', admin.site.urls),

]

crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('' , views.index , name= 'index'), #crud/
    path('new/' , views.new , name = 'new'), #crud/new
    # path('create/' , views.create , name='create'), #crud/create
    path('<int:art_pk>/', views.detail , name= 'detail'), #crud/detail하게 내용 보는 페이지
    path("<int:art_pk>/update/", views.update ,  name = 'update'), # crud/update/ 수정하는 페이지
    # path("<int:pk>/revise/" , views.revise , name = 'revise'),
    path("<int:art_pk>/delete/" , views.delete , name = 'delete'),
    path("<int:art_id>/comment" , views.comment , name='comment'),
    #부모의 아이디는 art_id로 바꿔주겠다. 
    path('<int:art_id>/comment/<int:com_id>/edit/' , views.comedit, name = 'comedit'),
    path('<int:art_id>/comment/<int:com_id>/del/' , views.comdel, name = 'comdel'),

]

btest/models.py
from django.db import models

# Create your models here.
class Btest(models.Model):
    btest_id = models.CharField(max_length=20 , null=True)
    question = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return {self.question}

class Btestchild(models.Model):
    btestchild_id = models.CharField(max_length=20 , null=True)
    survey = models.CharField(max_length=200)
    question = models.ForeignKey(Btest , on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default = 0)
    def __str__(self):
        return {self.survey}

btest/views.py
from django.shortcuts import render , redirect
from .models import Btest , Btestchild

# Create your views here.
def index(request):
    content = Btest.objects.all()
    context = {
        'question_all' : content
    }
    return render(request , 'btest/index.html' , context)

def create(request):
    if request.method == "POST":
        content = request.POST.get('content')
        btest = Btest()
        btest.question = content
        btest.save()

        return redirect('btest:index')

    else:
        return render(request, "btest/create.html")

def detail(request, btest_id):
    
    question = Btest.objects.get(id=btest_id)
    #자식테이블명_set
    #부모 테이블을 가진 모든 자식 테이블을 가져 온다.
    question_vote = question.btestchild_set.all() 

   
    context= {
        "question" : question,
        "question_vote" : question_vote
    }
    return render(request, "btest/detail.html" ,context )

def survey(request, btest_id):
    q = Btest.objects.get(id=btest_id)
    text = request.POST.get('detailadd')
    ques = Btestchild()
    ques.survey = text
    ques.question = q # 부모테이블에 저장,  FK이기 때문에 필수
    ques.save()
``
    return redirect('btest:detail' , btest_id)

def survey_mod(request , btestchild_id ):
    ques = Btestchild.objects.get(id=btestchild_id)
    
    if request.method =="POST":
        
        text = request.POST.get('detailadd')
        ques.survey = text
        ques.save()

        return redirect('btest:detail' ,ques.question_id )
    else:
        context = {
            "question_vote" : ques
        }
        return render(request, 'btest/survey_mod.html' , context )
    

btest/templates/btest/create.html
{% extends 'base.html' %}
{% block body %}
<form action='{% url "btest:create" %}' method = 'POST'>
    {% csrf_token %}
    <input type="text" name = "content" >
    <input type= 'submit' value = "질문 등록">
</form>
{% endblock %}

btest/templates/btest/detail.html
{% extends 'base.html' %}
{% block body %}

    {% csrf_token %}
    <h1>{{ question.question }}</h1>
  
    
    <hr>

    <ol>
        {% for vv in question_vote %}
        {{ vv.survey }}
        <li><a href="{% url 'btest:survey_mod' vv.id  %}">수정하기</a></li>
     
        {% empty %}
        등록된 투표가 없다.
        {% endfor %}
    </ol>
    <form action='{% url "btest:survey" question.id %}' method= 'POST'>
        {% csrf_token %}
        <input type="text" name = "detailadd">
        <input type='submit' value="항목추가">
    </form>
    

{% endblock %}

btest/templates/btest/index.html
{% extends 'base.html' %}
{% block body %}
<h1>질문 list</h1>
<ul>
{% for  con in   question_all  %}
    <li><a href="{% url 'btest:detail' con.id %}">{{  con.question }}</a></li>
{% endfor %}
</ul>
{% endblock %}

btest/templates/btest/survey_mod.html
{% extends 'base.html' %}
{% block body %}
<form action='' method= 'POST'>
    {% csrf_token %}
    <input type="text" name = "detailadd" value = "{{ question_vote.survey}}">
    <input type='submit' value = " 수정하기">
</form>
{% endblock %}