btest/urls.py
from django.urls import path
from . import views

app_name='btest'

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('create/' , views.create, name='create'),
    path('detail/<int:btest_id>/' , views.detail , name = 'detail'),
    path('survey/<int:btest_id>/' , views.survey , name='survey'),
    path('<int:btestchild_id>/survey_mod/', views.survey_mod , name = 'survey_mod'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
   
    path('btest/' ,include('btest.urls')),
    path('crud/' , include('crud.urls')),
    path('subway/' , include('subway.urls')),
    path('admin/', admin.site.urls),

]

crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('' , views.index , name= 'index'), #crud/
    path('new/' , views.new , name = 'new'), #crud/new
    # path('create/' , views.create , name='create'), #crud/create
    path('<int:art_pk>/', views.detail , name= 'detail'), #crud/detail하게 내용 보는 페이지
    path("<int:art_pk>/update/", views.update ,  name = 'update'), # crud/update/ 수정하는 페이지
    # path("<int:pk>/revise/" , views.revise , name = 'revise'),
    path("<int:art_pk>/delete/" , views.delete , name = 'delete'),
    path("<int:art_id>/comment" , views.comment , name='comment'),
    #부모의 아이디는 art_id로 바꿔주겠다. 
    path('<int:art_id>/comment/<int:com_id>/edit/' , views.comedit, name = 'comedit'),
    path('<int:art_id>/comment/<int:com_id>/del/' , views.comdel, name = 'comdel'),

]

subway/urls.py
from django.urls import path
from . import views

app_name = 'subway'
urlpatterns = [
    #name 을 설정하면 url관리가 수월하다.
    #{% url 'name설정한것' %} appname지정안했다면
    #{% url 'app_name:name설정한것' %} 위에 app name지정한다면
    #url이 바뀌어도 일일히 찾아서 바꿀 필요가 없다.
    path('' , views.index , name = 'index'),
    path('menu/' , views.menu , name='menu'), #메뉴 선택하는 링크
    # path('addmenu/' , views.addmenu, name = 'add'), #메뉴 추가 링크
    path('<int:id>/', views.detail , name = 'detail'),
    path('mod/<int:id>/' , views.mod , name  = 'mod'),
    path('delete/<int:id>/' , views.delete , name = "delete"),

    
]

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark">  
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="/subway/">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'subway:menu' %}">새 주문서</a>
                    <a class="nav-item nav-link" href="{% url 'crud:index' %}">뉴스 홈</a>
                    <a class="nav-item nav-link" href="{% url 'crud:new' %}">새 뉴스</a>
                    <a class="nav-item nav-link" href="{% url 'btest:index' %}">질문 홈</a>
                    <a class="nav-item nav-link" href="{% url 'btest:create' %}">새 질문</a>
                    
                    </div>
                </div> 
              </nav>

        {% block body %}
        {% endblock %}      
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>